### PR TITLE
Add the sidebar filter by date

### PR DESCRIPTION
**Pull request by jsfuentes**
How can i better access the eventTemplate variables? And why is all this js in the html file?

### CODE REVIEW

**Comment by tanzeelak** [comment]
Yeah I was going to make an issue for refactoring because all the map js is in the index file. 

I moved your function to the utils.js and it still works. Moving it into the main.js would involve refactoring to make dates and categories compatible with each other (lol I started categories too early). Where do you want me to keep the function?

**Comment by jsfuentes** [comment]
Yea, Ill make an issue for refactoring, its not that messy as there is pretty good comments so I could figure out how things work. And idk where to put it rn though, i trust your design decision

**Comment by jsfuentes** [comment]
Dont be afraid, it might be a backend problem

**Comment by TrinaKat** [comment]
image

https://github.com/ucladevx/Mappening-Backend/pull/40

**Pull request merged**
