### PR TITLE
Change default styling to SCSS.

### PR DESCRIPTION
**Pull request by wfehrnstrom**
I've changed the default stylesheet format used in this project from .css to .scss. This will enable various nifty SCSS only features: CSS style extensions, mixins, variables, and a variety of other cool features. Please see [Sass Guide](https://sass-lang.com/guide) as a starting point. While regular css files should still work (scss is compiled down into css), I recommend the use of scss files instead going forward.

### CODE REVIEW

**Comment by TrinaKat** [comment]
Not sure if this was finished that day, but LGTM. Fix the conflicting files and get approval from @tanzeelak and should be good.

**Comment by tanzeelak** [comment]
@wfehrnstrom Could you make a $default_border_color too? Otherwise this looks good

**Comment by TrinaKat** [comment]
NOTE: once this is merged, everyone will have to `yarn install`. Reminder to myself/anyone to tell everyone that

**Comment by wfehrnstrom** [comment]
I've made the changes requested. All gray borders are now set to a global variable $default_border_color = #d3d3d3

**Comment by wfehrnstrom** [comment]
Text-Outlines still appearing for certain elements:
Screen Shot 2019-05-03 at 4 12 27 PM

**Pull request merged**
